import Foundation
import Web3Core
import Web3

/// Arguments for the collateral controller's `withdrawAsset` call.
///
/// Two distinct salt/signature pairs travel here, and the contract names them differently from
/// Rain's API: the pair Rain's issuing API returns (`RainAdminSignature`) encodes into
/// `_executorPublisherSalt` / `_executorPublisherSignature`, while the wallet's own EIP-712
/// signature encodes into `_adminSalts` / `_adminSignatures` — the wallet is an admin of the
/// collateral. Field names here follow the roles, not the API's wording.
public struct WithdrawAssetParameter {
  /// Address of the collateral proxy contract
  public let proxyAddress: Web3Core.EthereumAddress

  /// Address of the ERC-20 token contract
  public let tokenAddress: Web3Core.EthereumAddress

  /// Withdrawal amount in base units (smallest denomination)
  public let amount: BigUInt

  /// Address of the recipient receiving the withdrawal
  public let recipientAddress: Web3Core.EthereumAddress

  /// Expiration timestamp (Unix timestamp)
  public let expiryAt: BigUInt

  /// Rain's executor-publisher salt (32 bytes), from `RainAdminSignature.salt`
  public let executorSalt: Data

  /// Rain's executor-publisher signature (65 bytes), from `RainAdminSignature.signature`
  public let executorSignature: Data

  /// The wallet's own EIP-712 salt (32 bytes), generated by `buildEIP712Message`
  public let walletSalt: Data

  /// The wallet's own signature over the EIP-712 message (65 bytes)
  public let walletSignature: Data

  public init(
    proxyAddress: Web3Core.EthereumAddress,
    tokenAddress: Web3Core.EthereumAddress,
    amount: BigUInt,
    recipientAddress: Web3Core.EthereumAddress,
    expiryAt: BigUInt,
    executorSalt: Data,
    executorSignature: Data,
    walletSalt: Data,
    walletSignature: Data
  ) {
    self.proxyAddress = proxyAddress
    self.tokenAddress = tokenAddress
    self.amount = amount
    self.recipientAddress = recipientAddress
    self.expiryAt = expiryAt
    self.executorSalt = executorSalt
    self.executorSignature = executorSignature
    self.walletSalt = walletSalt
    self.walletSignature = walletSignature
  }
}
